import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import "./loco.css";
import BgVideo from "@/component/reuseable/BgVideo";
import Loco from "@/component/Loco";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <BgVideo />
        <Loco >
          <div id="main" className=" relative z-10">
          {children}
          </div>
        </Loco>
      </body>
    </html>
  );
}
